s = open(r'C:\Users\Zarif\Downloads\24_demo (8).txt').readline()
print(s.find('YXYXYZXYXYXYZXZYXZYZYXYXYXZXYZYXYX'))
print(s[81865:81910])
s = s.replace('YY', '#')
s = s.replace('ZZ', '#')
s = s.replace('XX', '#')
s = s.split('#')
print(max(s, key=len))
print(len(max(s, key=len)))