# import re
# s = open(r'C:\Users\Zarif\Downloads\1062_1 (7).txt').readline()
# s = s.replace('FGSW', '#')
# m = re.finditer(r'(?=((?:\w*#){85}\w*))', s)
# mx_ln = []
# for x in m:
#     if len(x.group(1)) == 1186:
#         print(x.group(1))
#         break
#     #mx_ln.append(len(x.group(1)))
# # print(max(mx_ln))
s = 'QRSQFSRQRSQFSRQ#QRSQFSRQRSQFSRQRSQFSRQ#Q#QRSQFSRQRSQFSRQRSQGRQQRGRQ#QRSQFSRQRSQGRQFSRQRSQGRQQRGRQ#QRSQFSRQRSQFSRQ#QRSQFSRQRSQFSRQRSQFSRQRSQFSRQRSQFSRQRSQFSRQRSQGRQFSRQ#QRSQFSRQRSQFSRQRSQFSRQRSQFSRQRSQFSRQ#QRSQFSRQRSQGRQFSRQ#QRSQFSRQRSQFSRQRSQFSRQ#Q#QFSRQRSQFSRQRSQFSRQRSQFSRQRSQFSRQ#QRSQFSRQRSQFSRQRSQFSRQRSQFSRQRSQGRQQRGRQ#QRSQFSRQRSQGRQFSRQRSQFSRQ#QRSQFSRQ#Q#QRSQFSRQ#QRSQFSRQ#Q#QRSQFSRQRSQFSRQRSQFSRQRSQFSRQRSQFSRQRSQFSRQRSQFSRQ#QRSQFSRQRSQFSRQRSQFSRQ#QRSQFSRQRSQFSRQRSQFSRQ#QRSQFSRQ#QRSQFSRQ#Q#QRSQFSRQRSQFSRQ#QFSRQRSQFSRQRSQFSRQ#QRSQFSRQRSQFSRQ#Q#Q#Q#Q#QRSQFSRQRSQFSRQRSQFSRQRSQFSRQRSQFSRQ#QRSQFSRQRSQFSRQ#QRSQFSRQ#QRSQFSRQRSQFSRQ#Q#Q#QRSQGRQQRGRQ#Q#QRSQFSRQ#QRSQFSRQRSQFSRQRSQFSRQRSQFSRQ#QRSQFSRQ#QRSQFSRQ#QRSQGRQFSRQRSQFSRQRSQFSRQ#QFSRQRSQFSRQRSQFSRQRSQFSRQRSQFSRQRSQFSRQRSQFSRQ#QRSQFSRQ#Q#Q#Q#QRSQFSRQ#Q#QRSQFSRQ#QRSQFSRQRSQFSRQRSQFSRQ#QRSQFSRQRSQFSRQRSQFSRQ#Q#Q#QRSQFSRQRSQFSRQ#QRSQFSRQRSQFSRQRSQFSRQRSQFSRQRSQFSRQRSQFSRQ#Q#QRSQFSRQ#QRSQFSRQ#QRSQFSRQRSQFSRQ#Q#Q#QRSQFSRQ#QRSQFSRQRSQFSRQ#QRSQFSRQRSQFSRQ#QRSQFSRQRSQFSRQ#QRSQGRQFSRQ#Q#QRSQFSRQ#Q#QRSQFSRQRSQFSRQRSQFSRQ#Q#QFSRQRSQFSRQRSQFSRQRSQGRQQRGRQ#Q#QQRGRQRSQGRQFSRQ#Q#Q#QRSQFSRQ#QRSQFSRQ#QRSQFSRQRSQFSRQ#Q#QRSQFSRQ#QRSQGFSRQ'
s = s.replace('#', 'FGSW')
print(s)